text = input("what text would you like to decode to ostyn cipher: ")

text = text.replace("~", "a")
text = text.replace("%", "b")
text = text.replace("[", "c")
text = text.replace("`", "d")
text = text.replace("(", "e")
text = text.replace("{", "f")
text = text.replace("?", "g")
text = text.replace("|", "h")
text = text.replace(";", "i")
text = text.replace(":", "j")
text = text.replace("&", "k")
text = text.replace("-", "l")
text = text.replace("@", "m")
text = text.replace("$", "n")
text = text.replace(".", "o")
text = text.replace(")", "p")
text = text.replace("“", "q")
text = text.replace(">", "r")
text = text.replace("+", "s")
text = text.replace("/", "t")
text = text.replace("]", "u")
text = text.replace("}", "v")
text = text.replace("!", "w")
text = text.replace("_", "x")
text = text.replace("#", "y")

#due to pythons syntax theres 2 backward slashes
text = text.replace("\\", "z")

print(text)