menu = """
[1] Encode
[2] Decode
"""
print(menu)
choice = input("choice> ")


if choice == "1":
    foo = input("what text do you wanna encode> ")
    foo = foo.lower()
    foo = foo.replace("a", "000 ")
    foo = foo.replace("b", "001 ")
    foo = foo.replace("c", "002 ")
    foo = foo.replace("d", "010 ")
    foo = foo.replace("e", "011 ")
    foo = foo.replace("f", "012 ")
    foo = foo.replace("g", "020 ")
    foo = foo.replace("h", "021 ")
    foo = foo.replace("i", "022 ")
    foo = foo.replace("j", "100 ")
    foo = foo.replace("k", "101 ")
    foo = foo.replace("l", "102 ")
    foo = foo.replace("m", "110 ")
    foo = foo.replace("n", "111 ")
    foo = foo.replace("o", "112 ")
    foo = foo.replace("p", "120 ")
    foo = foo.replace("q", "121 ")
    foo = foo.replace("r", "122 ")
    foo = foo.replace("s", "200 ")
    foo = foo.replace("t", "201 ")
    foo = foo.replace("u", "202 ")
    foo = foo.replace("v", "210 ")
    foo = foo.replace("w", "211 ")
    foo = foo.replace("x", "212 ")
    foo = foo.replace("y", "220 ")
    foo = foo.replace("z", "221 ")
    print(f"your encoded text is: {foo}")
    exit()

if choice == "2":
    foo = input("what ostynV2 do you wanna decode> ")
    foo = foo.replace("000", "a")
    foo = foo.replace("001", "b")
    foo = foo.replace("002", "c")
    foo = foo.replace("010", "d")
    foo = foo.replace("011", "e")
    foo = foo.replace("012", "f")
    foo = foo.replace("020", "g")
    foo = foo.replace("021", "h")
    foo = foo.replace("022", "i")
    foo = foo.replace("100", "j")
    foo = foo.replace("101", "k")
    foo = foo.replace("102", "l")
    foo = foo.replace("110", "m")
    foo = foo.replace("111", "n")
    foo = foo.replace("112", "o")
    foo = foo.replace("120", "p")
    foo = foo.replace("121", "q")
    foo = foo.replace("122", "r")
    foo = foo.replace("200", "s")
    foo = foo.replace("201", "t")
    foo = foo.replace("202", "u")
    foo = foo.replace("210", "v")
    foo = foo.replace("211", "w")
    foo = foo.replace("212", "x")
    foo = foo.replace("220", "y")
    foo = foo.replace("221", "z")
    foo = foo.replace(" ", "")
    print(f"your decoded text is: {foo}")
    exit()


else:
    print("ERROR!")
